### ISSUE TITLE
404 error while uploading

### ISSUE THREAD

**Issue by Stan92** [showes/NgFlowSample#5]
Hi guys.
At first, I thank you for the code..
It works for me but I have some 404 errors while uploading a file.
Could you please tell me why that happens and what I have to do to fix them?
Thanks once again.
![flowbasic](https://cloud.githubusercontent.com/assets/1044972/10011818/62d18e18-6100-11e5-8249-9813d6bfd05d.PNG)

**Comment by samhowes** [comment]
Hi, thanks for using the code. 

It is important to remember that a 404 is a positive RESTful response. In this case, this 404 is an important part of the flow process. The client side sends a GET request for a specific chunk, then, if the server returns a 200, no action for that chunk is necessary. If the server returns a 404, that means that the server is missing that chunk and it needs to be uploaded. Upon receiving the 404, the client side then uploads the chunk in question. This is continued for every chunk. This process is how you can have multiple threads, or browser windows uploading the same file in the most efficient way, and the way that flow designed it. 

If you set a breakpoint in FileUploadController in the method TestFlowChunk you will see the logic performed on the server side. If your breakpoint doesn't get hit however, then there is a real bug.

**Comment by Stan92** [comment]
It's very clear... I thank you for the explanations.
