### ISSUE TITLE
Addition Param

### ISSUE THREAD

**Issue by Stan92** [showes/NgFlowSample#6]
Hi,
It should be a stupid question but..
I would like to create a temporary folder from a data sent by the addtionalData

Currently from the controller, I have
var uploadProcessor = new FlowUploadProcessor("~/App_Data/Tmp/FileUploads");

How can I concatenate the extra param at this point?
Something like 
var uploadProcessor = new FlowUploadProcessor("~/App_Data/Tmp/FileUploads" + myParam );

Any help?

**Comment by samhowes** [comment]
Duplicate of #4
